config/routes.rb
Velocipede::Application.routes.draw do

  devise_for :users
  netzke

  root :to => 'time_entries#new'

  get 'admin/index', to: 'panel#index', as: "admin_index"

  get 'bikes/new', to: 'bikes#new', as: "new_bike"
  get 'bikes/:id', to: 'bikes#show', as: "bike"

  get  'task_lists/:id/edit' => "task_lists#edit", as: "edit_task_list"

  get  'time_entries'     => "time_entries#index", as: "time_entries"
  get  'time_entries/new' => "time_entries#new",   as: "new_time_entry"

  ###########################
  # API Routes
  scope 'api', :module => :api, defaults: {format: :json} do
    scope 'v1', :module => :v1 do
      post 'checkin'  => "logs#checkin",  :as => "api_checkin"
      post 'checkout' => "logs#checkout", :as => "api_checkout"

      post 'reset'    => "users#password_reset", :as => "api_password_reset"

      get  'bikes/:id'    => "bikes#show",   as: "api_bike"
      post 'bikes/create' => "bikes#create", as: "api_create_bike"

      get  'task_lists/:id' => "task_lists#show",   as: "api_task_list"

      put  'tasks/update' => "tasks#update", as: "api_update_task"

      post 'time_entries/create' => "time_entries#create", as: "api_create_time_entry"
      delete 'time_entries/:id' => "time_entries#delete", as: "api_delete_time_entry"
    end
  end

end

app/models/acts_as_loggable/bike_action.rb
class ActsAsLoggable::BikeAction < ActiveRecord::Base
  attr_accessible :action
  has_many :logs

  def to_s
    self.action
  end
end

app/models/acts_as_loggable/bike_actions.rb
class ActsAsLoggable::BikeActions < ActiveRecord::Base
  #set_fixture_class :bike_actions => ActsAsLoggable::BikeActions
  attr_accessible :action
  
  belongs_to :bike
end

app/models/bike.rb
class Bike < ActiveRecord::Base
  acts_as_loggable
  attr_accessible :shop_id, :serial_number, :bike_brand_id, :bike_model_id, :model, :color, :bike_style_id,
    :seat_tube_height, :top_tube_length, :bike_wheel_size_id, :value, :bike_condition_id, :bike_purpose_id, :photo

  has_many :transactions

  has_one :owner, :class_name => 'User'
  has_one :task_list, :as => :item, :dependent => :destroy
  belongs_to :bike_brand
  belongs_to :bike_model
  belongs_to :bike_style
  belongs_to :bike_condition
  belongs_to :bike_purpose
  belongs_to :bike_wheel_size

  has_attached_file :photo, :styles => {:thumb => '100x100>'}

  validates :shop_id, :presence => true, :uniqueness => true, :numericality => { :only_integer => true }
  validates :serial_number, :length => { :minimum => 3 }
  validates :model, :length => { :maximum => 50 }
  validates :bike_brand_id, :presence => true, :numericality => { greater_than: 0, message: "is not a valid brand" }
  #validates :color, :presence => true
  validates :bike_style_id, :presence => true, :numericality => { greater_than: 0, message: "is not a valid style" }
  validates :seat_tube_height, :presence => true, :numericality => true
  validates :bike_wheel_size_id, :presence => true, :numericality => { greater_than: 0, message: "is not a valid wheel size" }
  validates :bike_condition_id, :presence => true, :numericality => { greater_than: 0, message: "is not a valid condition" }
  validates :bike_purpose_id, :presence => true, :numericality => { greater_than: 0, message: "is not a valid purpose" }

  validates_attachment :photo,  :content_type => {:content_type => %w{ image/jpeg image/gif image/png }},
                                :file_name => {:matches => [/png\Z/, /jpe?g\Z/, /gif\Z/]}

  self.per_page = 15

  after_create :create_task_list

  def brand
    self.bike_brand
  end

  def style
    self.bike_style
  end

  def condition
    self.bike_condition
  end

  def purpose
    self.bike_purpose
  end

  def wheel_size
    self.bike_wheel_size
  end

  def to_s
    "#{brand} - #{model} - #{style}"
  end

  def create_task_list
    TaskList.create( item_id: self.id, item_type: self.class.to_s, name: "Safety Checklist")
  end
end

app/controllers/api/v1/bikes_controller.rb
class Api::V1::BikesController < Api::V1::BaseController
  CANNOT_MANAGE = "You do not have permission to manage bikes."
  EXPECTED_BIKE = "Expected bike in submitted data"
  NOT_FOUND = "The bike could not be found."

  before_filter :check_bike_permission, except: :show

  def create
    if params[:bikes] && bike = params[:bikes].first
      @bike = Bike.new(bike)
      if !@bike.save
        render json: { errors: @bike.errors }, status: 422 and return
      end
    else
        render json: { errors: [EXPECTED_BIKE]}, status: 422 and return
    end
  end

  def show
    @bike = Bike.find_by_id(params[:id])
    if @bike.nil?
      render json: { errors: [NOT_FOUND] }, status: 404 and return
    end
  end

  private
    def check_bike_permission
      if cannot? :manage, Bike
        render json: { errors: [CANNOT_MANAGE]}, status: 403 and return
      end
    end
end

app/controllers/bikes_controller.rb
class BikesController < AuthenticatedController

  def new
    @bike = Bike.new bike_purpose_id: 1
    @brands = BikeBrand.all.map{ |b| [b.brand, b.id] }
    @brands.unshift( ["Select a brand", -1] )
    @wheel_sizes = BikeWheelSize.all.map{ |w| [w.display_string, w.id] }
    @wheel_sizes.unshift( ["Select a wheel size", -1] )
  end

  def show
    @bike = Bike.find_by_id(params[:id])
    @task_list = @bike.task_list
    @show_add_bike = true if params[:add_bike]
  end

end

app/views/bikes/new.html.haml
= top_menu

%h1 Add Bike

.row
  .col-xs-12.col-sm-6.col-lg-4
    = form_for @bike, as: 'bikes', index: '', url: api_create_bike_path, method: :post, enctype: 'multipart/form-data', html: {id: 'add_bike_form'} do |f|
      = f.hidden_field 'bike_purpose_id'
      %fieldset
        .form-group
          = f.number_field 'shop_id', placeholder: 'Shop ID', min: 0, class: 'form-control', id: 'shop_id'
          .help-block

        .form-group
          = f.select 'bike_brand_id', options_for_select(@brands), {}, class: 'form-control', id: 'bike_brand_id'
          .help-block

        .form-group
          = f.text_field 'model', placeholder: 'Model', class: 'form-control', id: 'model'
          .help-block

        .form-group
          = f.text_field 'serial_number', placeholder: 'Serial Number', class: 'form-control', id: 'serial_number'
          .help-block

        .form-group
          .btn-group(data-toggle="buttons")
            %label.btn.btn-default
              = f.radio_button 'bike_style_id', 3
              RD
            %label.btn.btn-default
              = f.radio_button 'bike_style_id', 1
              MTN
            %label.btn.btn-default
              = f.radio_button 'bike_style_id', 2
              HYB
            %label.btn.btn-default
              = f.radio_button 'bike_style_id', 4
              OTHER
          = hidden_field_tag nil, nil, id: 'bike_style_id'
          .help-block

        .form-group
          = f.select 'bike_wheel_size_id', options_for_select(@wheel_sizes), {}, class: 'form-control', id: 'bike_wheel_size_id'
          .help-block

        .form-group
          .btn-group(data-toggle="buttons")
            %label.btn.btn-default
              = f.radio_button 'bike_condition_id', 2
              Poor
            %label.btn.btn-default
              = f.radio_button 'bike_condition_id', 3
              Fair
            %label.btn.btn-default
              = f.radio_button 'bike_condition_id', 4
              Good
            %label.btn.btn-default
              = f.radio_button 'bike_condition_id', 5
              Excellent
          = hidden_field_tag nil, nil, id: 'bike_condition_id'
          .help-block

        .form-group
          .input-group
            = f.number_field 'seat_tube_height', placeholder: 'Seat Tube', min: 0, max: 100, class: 'form-control', id: 'seat_tube_height'
            .input-group-addon cm
          .help-block

        .form-group
          %label Bike photo (optional)
          = f.file_field 'photo', id: 'photo'
          .help-block

        -# Commenting this out until description is added to Bike
          /.form-group
            %input{id: "bike_description", placeholder: "Short description", type: "text", class: "input-lg" }

        .form-group
          = button_tag 'Add Bike', class: 'btn btn-primary'

app/views/bikes/show.html.haml
- btn = if @show_add_bike
  - capture do
    = link_to 'Add Another Bike?', new_bike_path, class: 'btn btn-default navbar-btn hidden-xs'
    = link_to new_bike_path, class: 'navbar-brand visible-xs', title: 'Add Another Bike?' do
      %i.glyphicon.glyphicon-plus

= top_menu btn

%h1 #{@bike.shop_id}: #{@bike.bike_brand}
%h4= @bike.model

.form-horizontal
  - if @bike.photo?
    .form-group
      %label.col-sm-2.control-label Photo
      .col-sm-10
        = link_to @bike.photo.url, target: '_blank' do
          %img{src: @bike.photo.url(:thumb),  class: 'img-thumbnail'}

  .form-group
    %label.col-sm-2.control-label Type
    .col-sm-10.form-control-static= @bike.bike_style

  .form-group
    %label.col-sm-2.control-label Wheel Size
    .col-sm-10.form-control-static= @bike.bike_wheel_size.display_string

  .form-group
    %label.col-sm-2.control-label Condition
    .col-sm-10.form-control-static= @bike.bike_condition

  .form-group
    %label.col-sm-2.control-label Seat Tube (cm)
    .col-sm-10.form-control-static= @bike.seat_tube_height

  .form-group
    %label.col-sm-2.control-label Purpose
    .col-sm-10.form-control-static= @bike.bike_purpose

  - unless @bike.value.nil?
    .form-group
      %label.col-sm-2.control-label Value
      .col-sm-10.form-control-static= @bike.value

  - unless @bike.color.nil?
    .form-group
      %label.col-sm-2.control-label Color
      .col-sm-10.form-control-static
        .bike-color(style="background-color: ##{@bike.color}")= @bike.color

  - if @task_list
    - tasks = @task_list.tasks.to_a
    .form-group
      %label.col-sm-2.control-label Task list
      .col-sm-10.form-control-static
        = link_to edit_task_list_path(@task_list.id) do
          #{tasks.select(&:done).count}/#{tasks.count}