config/routes.rb
Velocipede::Application.routes.draw do

  devise_for :users
  netzke

  root :to => 'time_entries#new'

  get 'admin/index', to: 'panel#index', as: "admin_index"

  get 'bikes/new', to: 'bikes#new', as: "new_bike"
  get 'bikes/:id', to: 'bikes#show', as: "bike"

  get  'task_lists/:id/edit' => "task_lists#edit", as: "edit_task_list"

  get  'time_entries'     => "time_entries#index", as: "time_entries"
  get  'time_entries/new' => "time_entries#new",   as: "new_time_entry"

  ###########################
  # API Routes
  scope 'api', :module => :api, defaults: {format: :json} do
    scope 'v1', :module => :v1 do
      post 'checkin'  => "logs#checkin",  :as => "api_checkin"
      post 'checkout' => "logs#checkout", :as => "api_checkout"

      post 'reset'    => "users#password_reset", :as => "api_password_reset"

      get  'bikes/:id'    => "bikes#show",   as: "api_bike"
      post 'bikes/create' => "bikes#create", as: "api_create_bike"

      get  'task_lists/:id' => "task_lists#show",   as: "api_task_list"

      put  'tasks/update' => "tasks#update", as: "api_update_task"

      post 'time_entries/create' => "time_entries#create", as: "api_create_time_entry"
      delete 'time_entries/:id' => "time_entries#delete", as: "api_delete_time_entry"
    end
  end

end

app/models/time_entry.rb
class TimeEntry < ActsAsLoggable::Log
  default_scope where( loggable_type: "User",
                       logger_type: "User",
                       log_action_type: "ActsAsLoggable::UserAction").where("log_action_id != 4").order("start_date DESC")

  def copy_to_bike_history(bike_id)
    self.assign_attributes({
          copy_log: true,
          copy_type: 'Bike',
          copy_id: bike_id,
          copy_action_type: 'ActsAsLoggable::BikeAction',
          copy_action_id: 4
        })
  end

  def duration
    end_date - start_date
  end

  def duration_in_hours
    (duration / 1.hour).round(2)
  end

  def type
    log_action.try(:action)
  end
end

app/controllers/api/v1/time_entries_controller.rb
class Api::V1::TimeEntriesController < Api::V1::BaseController
  EXPECTED_TIME_ENTRY = "Expected time entry in submitted data"
  NOT_FOUND = "Time entry not found"

  def create
    if params[:time_entries] && time_entry = params[:time_entries].first
      time_entry.merge!({ loggable_id: current_user.id,
                          logger_id: current_user.id  })
      bike_id = time_entry[:bike_id].to_i

      @time_entry = TimeEntry.new(time_entry.except(:bike_id))

      if bike_id > 0
        @time_entry.copy_to_bike_history(bike_id)
      end

      if !@time_entry.save
        render json: { errors: @time_entry.errors }, status: 422 and return
      end
    else
      render json: { errors: [EXPECTED_TIME_ENTRY]}, status: 422 and return
    end
  end

  def delete
    if time_entry = TimeEntry.find_by_id(params[:id])
      time_entry.delete
      render nothing: true, status: 204 and return
    else
      render json: { errors: [NOT_FOUND]}, status: 404 and return
    end
  end
end

app/controllers/time_entries_controller.rb
class TimeEntriesController < AuthenticatedController

  def new
    @bikes = Bike.all.map{ |b| [b.to_s , b.id] }
    if bike = current_user.bike
      @bikes.unshift( [bike.to_s, bike.id] )
    end
    @bikes.unshift( ["Non-bike work", -1] )
  end

  def index
    @user_time_entries = TimeEntry.where(loggable_id: current_user.id)
    @credits_available = current_user.total_credits
    @hours_worked = current_user.total_hours
  end
end

app/views/time_entries/index.haml
= top_menu

%h1 Your Timesheet

.row
  .col-xs-12.col-sm-6.col-lg-3
    %p
      %span.badge= @hours_worked
      Total Hours Worked

  .col-xs-12.col-sm-6.col-lg-3
    %p
      %span.badge= @credits_available
      Total Credits Available

%table.table
  %tbody
    - @user_time_entries.each do |entry|
      -# data: {start_date: ..} gets transformed to data-start-date instead of data-start_date, we don't want this
      %tr{data: {id: entry.id, description: entry.description, duration: entry.duration_in_hours},
          'data-start_date' => entry.start_date.to_date.to_formatted_s(:rfc822)}
        %td= entry.start_date.to_date.to_formatted_s(:rfc822)
        %td= entry.duration_in_hours
        %td= entry.type
        %td= link_to truncate(entry.description).presence || '<em>No title</em>'.html_safe, edit_task_list_path(entry)
        %td
          = link_to '#modal', class: 'text-danger work_entry-delete-btn', role: 'button', data: {toggle: 'modal', target: '#confirmation'} do
            %i.glyphicon.glyphicon-remove

= link_to 'Add Time Entry', new_time_entry_path, class: 'btn btn-primary'

.modal#confirmation(role="dialog" aria-labelledby="confirmation_title" aria-hidden="true" tabindex="-1")
  .modal-dialog
    .modal-content
      .modal-header
        %button.close(data-dismiss="modal" aria-hidden="true") &times;
        %h4#confirmation_title Are you sure you want to delete?
      .modal-body
        #work_entry_start_date Start Date
        #work_entry_duration Duration
        #work_entry_description Description
      .modal-footer
        %button.btn.btn-default(data-dismiss="modal" aria-hidden="true") Cancel
        %button.btn.btn-danger#confirmation_delete{data: {url_template: api_delete_time_entry_path('__ID__')}} Delete

app/views/time_entries/new.haml
= top_menu

%h1 Add Time Entry
- time = Time.now
- date_format, time_format = '%m/%d/%Y', '%l:%M %p'
- mjs_date_format, mjs_time_format = 'MM/DD/YYYY', 'h:mm A'

.row
  .col-xs-12.col-sm-6.col-lg-4
    %fieldset
      .form-group.form-inline
        = text_field_tag nil, time.strftime(date_format), id: 'date_id', placeholder: 'Date', class: 'form-control',
                                                          size: 12, data: {format: mjs_date_format}
        .help-block

      .form-group.timepickers.form-inline
        .form-group
          %label.visible-xs Start time
          = text_field_tag nil, time.strftime(time_format), id: 'start_time_id', placeholder: 'Start time',
                                                            class: 'form-control', size: 8, data: {format: mjs_time_format}
          .hidden#start_date
          .help-block

        .form-group.dash.hidden-xs
          &mdash;

        .form-group
          %label.visible-xs End time
          = text_field_tag nil, time.strftime(time_format), id: 'end_time_id', placeholder: 'End time',
                                                            class: 'form-control', size: 8, data: {format: mjs_time_format}
          .hidden#end_date
          .help-block

      .form-group
        .btn-group(data-toggle="buttons")
          %label.btn.btn-default
            = radio_button_tag 'action_id', 1, false, autocomplete: 'off'
            Volunteer
          %label.btn.btn-default
            = radio_button_tag 'action_id', 2, false, autocomplete: 'off'
            Personal
          %label.btn.btn-default
            = radio_button_tag 'action_id', 3, false, autocomplete: 'off'
            Staff
        .hidden#log_action_id
        .help-block

      .form-group
        = select_tag :bike_id, options_for_select(@bikes), class: 'form-control'

      .form-group
        = text_area_tag nil, nil, id: 'description_id', placeholder: 'Work description', class: 'form-control', rows: 5

      .control-group
        .controls
          = button_tag 'Add Time Entry', id: 'add_time_entry_submit', class: 'btn btn-primary', data: {url: api_create_time_entry_path, forward: '.'}