config/routes.rb
Velocipede::Application.routes.draw do

  devise_for :users
  netzke

  root :to => 'time_entries#new'

  get 'admin/index', to: 'panel#index', as: "admin_index"

  get 'bikes/new', to: 'bikes#new', as: "new_bike"
  get 'bikes/:id', to: 'bikes#show', as: "bike"

  get  'task_lists/:id/edit' => "task_lists#edit", as: "edit_task_list"

  get  'time_entries'     => "time_entries#index", as: "time_entries"
  get  'time_entries/new' => "time_entries#new",   as: "new_time_entry"

  ###########################
  # API Routes
  scope 'api', :module => :api, defaults: {format: :json} do
    scope 'v1', :module => :v1 do
      post 'checkin'  => "logs#checkin",  :as => "api_checkin"
      post 'checkout' => "logs#checkout", :as => "api_checkout"

      post 'reset'    => "users#password_reset", :as => "api_password_reset"

      get  'bikes/:id'    => "bikes#show",   as: "api_bike"
      post 'bikes/create' => "bikes#create", as: "api_create_bike"

      get  'task_lists/:id' => "task_lists#show",   as: "api_task_list"

      put  'tasks/update' => "tasks#update", as: "api_update_task"

      post 'time_entries/create' => "time_entries#create", as: "api_create_time_entry"
      delete 'time_entries/:id' => "time_entries#delete", as: "api_delete_time_entry"
    end
  end

end

app/views/site/index.html.haml
%h1 Dashboard

.row.fieldset
  .col-xs-12.col-sm-3.col-lg-2
    %p= link_to 'Add Time Entry', new_time_entry_path, class: 'btn btn-default btn-block'
  .col-xs-12.col-sm-3.col-lg-2
    %p= link_to 'View Timesheet', time_entries_path, class: 'btn btn-default btn-block'

- can_manage_bike = can? :manage, Bike
- has_bike = !@bike.nil?
- if can_manage_bike || has_bike
  .row.fieldset
    - if can_manage_bike
      .col-xs-12.col-sm-3.col-lg-2
        %p
          = link_to 'Add Bike', new_bike_path, class: 'btn btn-default btn-block'

    - if has_bike
      .col-xs-12.col-sm-3.col-lg-2
        %p
          = link_to 'View Your Bike', bike_path(@bike), class: 'btn btn-default btn-block'

.row.fieldset
  .col-xs-12.col-sm-3.col-lg-2
    %p
      = link_to 'Desktop View', admin_index_path, class: 'btn btn-default btn-block'

.row.fieldset
  .col-xs-12.col-sm-3.col-lg-2
    %p
      = button_tag 'Logout', id: 'index_logout', class: 'btn btn-danger btn-block', data: {url: destroy_user_session_path}